### ISSUE TITLE
Token Missing Error

### ISSUE THREAD

**Issue by maya329** [rocket-admin/rocketadmin#666]
**Describe the bug**
After spinning up the instance, I'm greeted with a Token missing error

**To Reproduce**
1. Go to the URL of rocketadmin
2. Observe a popup at the bottom left showing "Token is missing"

**Expected behavior**
To be able to login

**Screenshots**
<img width="642" alt="image" src="https://github.com/rocket-admin/rocketadmin/assets/68476468/de08aee5-868a-407a-91af-

**Desktop (please complete the following information):**
 - OS: macOS 14.4.1 (23E224)
 - Chrome, Safari, Brave

**Additional context**
I created and used the following docker compose

```
services:
    rocketadmin:
        image: rocketadmin/rocketadmin
        depends_on:
          - db
          - rocket_db
        restart: always
        container_name: infinity_rocket_admin
        ports:
            - '8034:80'
        environment:
            - 'APP_DOMAIN_ADDRESS=XXX'
            - 'TEMPORARY_JWT_SECRET=XXX'
            - 'PRIVATE_KEY=XXX'
            - 'JWT_SECRET=XXX'
            - 'DATABASE_URL=postgresql://xxx'
    db:
        image: mysql:8.0.23
        container_name: infinity_rocket_db
        ports:
          - 8035:3306
        volumes:
          - ./db_data:/var/lib/mysql
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: uqt1gef3QBY!qyd7xcx
          MYSQL_DATABASE: inifnity_lootbox
          MYSQL_USER: infi_rocket
          MYSQL_PASSWORD: xza3TFC@tub6jzy!mam

    rocket_db:
        image: postgres
        container_name: infinity_rocket_admin_db
        restart: always
        shm_size: 128mb
        volumes:
            - ./pg_data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: rocket_admin
            POSTGRES_PASSWORD: fdy3xng-cgb2DHW*qye
            POSTGRES_DB: infinity-rocket
```
